environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"

init:

install:
    - "%PYTHON%\\python.exe --version"
    - "%PYTHON%\\Scripts\\pip install https://github.com/williballenthin/vivisect/zipball/master"
    - "%PYTHON%\\Scripts\\pip install pyinstaller"
    - ps: Set-Content "floss\\version.py" ( "__version__ = '{0}'" -f ( git describe --tags --always ) )
    - "%PYTHON%\\Scripts\\pip install -e ."
    - "%PYTHON%\\Scripts\\pyinstaller floss.spec"
    - ps: Start-FileDownload 'https://s3.amazonaws.com/build-resources.floss.flare.fireeye.com/appveyor/verpatch.exe'
    - verpatch.exe "dist\\floss.exe" (git describe --tags --always).TrimStart("v") /va /high /langid 1033 /s description "FireEye Labs Obfuscated String Solver" /s company "FireEye" /s product "FLOSS"


build: off

artifacts:
    - path: "dist\\floss.exe"

deploy:
  - provider: S3
    access_key_id:
      secure: 62mhuS0Iui9H3jf/PdcZ3srxaX1frZacjH9SRIplljM=
    secret_access_key:
      secure: nP7uNhSUZZwamVfsS80Z+gBbMjSvAvYG/avK6pTKtH78jBcKeyfKFZSTM+siO6os
    bucket: build-artifacts.floss.flare.fireeye.com
    folder: appveyor
    #artifact:
    set_public: false
