language: python
python:
  - "2.7"

install:
    - pip install https://github.com/williballenthin/vivisect/zipball/master
    - pip install -e .
    - sudo apt-get install -y git clang mingw-w64 gcc-mingw-w64 cmake make gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 mingw-w64-dev
    - git clone https://github.com/tpoechtrager/wclang.git wclang
    - cd wclang && cmake -DCMAKE_INSTALL_PREFIX=/usr/local && make && sudo make install
    - cd tests/src && make all

script: nosetests
