language: python
python:
  - "2.7"

install:
    - pip install https://github.com/williballenthin/vivisect/zipball/master
    - pip install -e .
    - sudo apt-get install -y git clang mingw-w64 gcc-mingw-w64 cmake make gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 mingw-w64-dev  binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686
    - git clone https://github.com/tpoechtrager/wclang.git wclang
    - pushd wclang; cmake -DCMAKE_INSTALL_PREFIX=/usr/local && make && sudo make install; popd
    - pushd tests/src; make all; popd

script: py.test tests/src/
